name: CI
on: [push]
jobs: 
  test_build_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Run tests
        run : |
          pip install numpy
          pip install pytest
          pytest
      - name: build docker image
        run:
          docker build -t test .
      - name: run docker image
        run: docker run test
      - name: docker tag
        run: docker tag test:latest thetom09/ynov_test_unitaire:test_image
      - name: docker push
        run: docker push thetom09/ynov_test_unitaire:test_image